source 'https://rubygems.org'
ruby '2.0.0'

gem 'cinch'
gem 'nokogiri'
gem 'httparty'
gem 'json'
gem 'unirest'
gem 'soundcloud'
gem 'dotenv-heroku'
gem 'mechanize'
gem 'rapgenius'
gem 'cinch-identify'
