source 'https://rubygems.org'
ruby '2.2.3'

gem 'cinch'
gem 'nokogiri'
gem 'httparty'
gem 'json'
gem 'unirest'
gem 'soundcloud'
gem 'dotenv-heroku'
gem 'mechanize'
gem 'rapgenius'
gem 'cinch-identify'
gem 'unidecoder'
gem 'fuzzy-string-match'
gem 'wolfram-alpha'

gem 'pg'
gem 'heroku-api'
